# Configuration for Travis CI

# sudo is required for Docker calls
sudo: required

# mark our language as Python
language: node

# add dependent services
services:
  - docker

before_install: 
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
# main script
# for the push to work, the variables below must be set
# pushes to Heroku registry, app goes live from there
script:
  
  # build web files
  - npm install
  # login to Heroku registry
  - docker login -e="varadipeter9@gmail.com" -u="varadipeter" -p="7eaaf161-01de-4de6-9938-a464d3aa4c64" registry.heroku.com
  # build Docker image
  - docker build -t registry.heroku.com/iotwithchemdocker/web .
  # push Docker image to Heroku registry
  - docker push registry.heroku.com/iotwithchemdocker/web